process data:
  stage: build
  tags:
    - mozmeao
    - aws
  only:
    - dev
    - master
    - prod
  script:
    - docker-compose build --pull app
    - docker-compose run --rm --user "$(id -u)" app
    - ./push.sh
